// <auto-generated />
using System;
using ClaySmartLockSolution.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaySmartLockSolution.Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClaySmartLockSolution.Core.Entities.Door", b =>
                {
                    b.Property<long>("DoorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoorId"), 1L, 1);

                    b.Property<string>("DoorLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoorId");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            DoorId = 1L,
                            DoorLocation = "Office Door"
                        },
                        new
                        {
                            DoorId = 2L,
                            DoorLocation = "Tunnel"
                        });
                });

            modelBuilder.Entity("ClaySmartLockSolution.Core.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("DoorAccessTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClaySmartLockSolution.Core.Entities.UserDoorAccess", b =>
                {
                    b.Property<long>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccessId"), 1L, 1);

                    b.Property<bool>("AccessAtemptSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AccessDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("DoorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AccessId");

                    b.HasIndex("DoorId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDoorAccesses");
                });

            modelBuilder.Entity("ClaySmartLockSolution.Core.Entities.UserDoorAccess", b =>
                {
                    b.HasOne("ClaySmartLockSolution.Core.Entities.Door", "Door")
                        .WithMany("UserDoorAccesses")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaySmartLockSolution.Core.Entities.User", "User")
                        .WithMany("UserDoorAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaySmartLockSolution.Core.Entities.Door", b =>
                {
                    b.Navigation("UserDoorAccesses");
                });

            modelBuilder.Entity("ClaySmartLockSolution.Core.Entities.User", b =>
                {
                    b.Navigation("UserDoorAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
